global: 
  scrape_interval: 15s 
scrape_configs:
 - job_name: 'ohmgraphite'
   static_configs:
     - targets: ['192.168.0.142:63333']
       labels:
         hostname: 5520
         job: ohmgraphite
         is: 5520
